Add AWS AMI service discontinuation notice
kaiachain/kaia-docs pull request #158
Opened 2024-11-26 02:07 UTC by scott-klaytn

## Proposed changes

Add AWS AMI service discontinuation notice

## Types of changes

Please put an x in the boxes related to your change.

- [x] Minor Issues and Typos
- [ ] Major Content Contribution
- [ ] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to reach out. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [x] I have read the [CONTRIBUTING GUIDELINES](https://github.com/kaiachain/kaia-docs/blob/main/CONTRIBUTING.md)
- [x] I have read the [CLA](https://gist.github.com/kaiachain-dev/bbf65cc330275c057463c4c94ce787a6) and signed by comment ```I have read the CLA Document and I hereby sign the CLA``` in first time contribute
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Related issues

## Further comments

2024-11-26 02:10 UTC, blukat29 approved these changes
Thanks!

2024-11-26 05:51 UTC, 2dvorak commented
Thank you for the updates!
Should we remove [AWS AMI section](https://docs.kaia.io/learn/storage/block-sync/#aws-ami) in block sync page too?

2024-11-27 01:59 UTC, 2dvorak approved these changes

2024-11-27 03:59 UTC, 2dvorak requested changes
@scott-klaytn Scott, sorry but we've been notified that AWS AMI will not be updated anymore however the last AMIs will be kept. So users would be able to use the last AMIs which are created on Nov 2024, however should need extra time to sync up blocks after Nov 2024.

2024-11-27 05:12 UTC, 2dvorak approved these changes

2024-11-27 05:14 UTC, merged